### PR TITLE
Create tile entity topping

### PR DESCRIPTION
**Pull request by Pokechu22**
- Lists all tile entities
- Finds the update tile entity packet (all versions >= 13w41a)
- Lists the numeric ID used in the update tile entity packet
- Lists the blocks associated with each tile entity (1.9+)

### CODE REVIEW

**Comment by TkTech** [comment]
PEP8? :)

**Comment by Pokechu22** [comment]
Done except for some cases where lines are longer than 79 chars, because in those cases I feel like it would be more messy to try and split the line than to keep it as is.

**Comment by TkTech** [comment]
I'm an annoying stickler when it comes to PEP8, sorry about that. I'm also a stickler for 80 characters because [in python] I find if I'm going over that I've almost always made something more complex than it needs to be. This would be just fine for example (I think, just doing it on the phone :))

```
           # No reason to rebuild this string on each iteration (string appending 
           # is a historically evil thing in CPython although not so bad these days)
           nbt_tag_type = 'L' + aggregate['classes']['nbtcompound'] + ';'

           for packet in aggregate["packets"]["packet"].itervalues():
                if packet["direction"] != "CLIENTBOUND" or packet["state"] != "PLAY":
                    continue

                packet_cf = ClassFile(StringIO(jar.read(packet["class"])))
                # Check if the packet has the expected fields in the class file
                # for the update tile entity packet
                if (len(packet_cf.fields) >= 3 and
                        # Tile entity type int, at least (maybe also position)
                        len(list(packet_cf.fields.find(type_="I"))) and
                        # New NBT tag
                        len(list(packet_cf.fields.find_one(type_=nbt_tag_type))):
                    # There are other fields, but they vary by version.
                    updatepacket = packet
                    break
```

**Comment by Pokechu22** [comment]
How about this, though?

```
print("Trying to mark %s as a block with tile entity %s but that tile entity does not exist!" % (stack[0], stack[1]))
```

How should I split that onto multiple lines?  It seems like it's possible to split it, but I'm not sure how I should be doing that stylistically.  Should I be doing this:

```
print ("Trying to mark %s as a block with "
       "tile entity %s but that tile entity "
       "does not exist!" % (stack[0], stack[1]))
```

Or this:

```
print ("Trying to mark %s as a block with "
       "tile entity %s but that tile entity "
       "does not exist!"
       % (stack[0], stack[1]))
```

Or something else?

Also, with `packet.packetbuffer`, how do I split _that_?

**Comment by TkTech** [comment]
I completely forgot about this PR, my apologies @Pokechu22. Is this still up to date with the current jars?

**Comment by Pokechu22** [comment]
Yep, still up to date (including listing bed as a tile entity now, which it is).

**Pull request merged**
